name: DEPLOY DEV
permissions:
  contents: write
on:
  push:
    branches:
      - main

jobs:
  deploy-dev:
    environment: dev
    name: deploy dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: mkdir dist && cp -r Assets Gideollanos Logprox Seinpro Turing main.js index.html dist/

      - name: Deploy
        # https://github.com/JamesIves/github-pages-deploy-action
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist